const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"

const VIEW_REPORT = "VIEW_REPORT"

const VIEW_QUIZLIST = "VIEW_QUIZLIST"
const VIEW_STEPLIST = "VIEW_STEPLIST"
const VIEW_LAWLIST = "VIEW_LAWLIST"
const VIEW_RULELIST = "VIEW_RULELIST"

const VIEW_QUIZ = "VIEW_QUIZ"
const VIEW_STEP = "VIEW_STEP"
const VIEW_RULE = "VIEW_RULE"

const ADD_QUIZ = "ADD_QUIZ"
const ADD_STEP = "ADD_STEP"

const DELETE_QUIZ = "DELETE_QUIZ"
const DELETE_STEP = "DELETE_STEP"

const UPDATE_QUIZ = "UPDATE_QUIZ"
const UPDATE_STEP = "UPDATE_STEP"
const UPDATE_RULE = "UPDATE_RULE"
const UPDATE_ANSWER = "UPDATE_ANSWER"
